# Generated by Django 3.2.9 on 2021-11-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),                   
                ('marca', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('cantidad', models.CharField(max_length=50)),
                ('disponible', models.CharField(max_length=50)),
            ],
        ),
    ]
